### Support available at: sgrewritten.org/discord ################################ Version: ${project.version}
# +-,┌-.¸-┌─┬┬─┐-- . -- ,┬┬-.¸ - ,┌-.¸ --- ô -- ┌─┬┬─┐-·┌┬───┐---- ▄▄▄ - ‚——. -▄--▄-▄--▄-▄-▄▄▄▄▄-+ #
# | ``=ı¸   ||    /\\    ||__;  |(  __¸   /\\     ||    |├--:      █▄▄▀ (“‡‡”) █▄▄▀ █▄▄▀ █   █   | #
# | :¸_|;  ,||. ¸/¯¯)\¸ ¸||¯)\¸  \\__|; ¸/¯¯)\¸  ,||.  ,||,,,;     █▄▄█  \__/  █  █ █  █ █   █   | #
# +--------------------------------------{OFFICIAL MODULE}---------------------------------------+ #
# |               _____ _   _ _______ ______ _____  ______      _____ ______  _____              | #
# |              |_   _| \ | |__   __|  ____|  __ \|  ____/\   / ____|  ____|/ ____|             | #
# |                | | |  \| |  | |  | |__  | |__) | |__ /  \ | |    | |__  | (___               | #
# |                | | | . ` |  | |  |  __| |  _  /|  __/ /\ \| |    |  __|  \___ \              | #
# |               _| |_| |\  |  | |  | |____| | \ \| | / ____ \ |____| |____ ____) |             | #
# |              |_____|_| \_|  |_|  |______|_|  \_\_|/_/    \_\_____|______|_____/              | #
# |______________________________________________________________________________________________| #
# |                                 sgrewritten.org/interfaces                                   | #
# +----------------------------------------------+-----------------------------------------------+ #
# |    Documentation: sgrewritten.org/infoSGI    |     Bug Reports: sgrewritten.org/bugsSGI      | #
# +----------------------------------------------+-----------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# What language will this module use when communicating with your users?
# Supported languages [en].
#
# If SGM isn't yet available in your language, please consider becoming a translator:
# https://crowdin.com/project/stargate-bukkit
language: "en-US"

# +----------------------------------------------------------------------------------------------+ #
# |                                       Aesthetic Tweaks                                       | #
# +----------------------------------------------------------------------------------------------+ #
icon:
  # The "icon" used to mark a Stargate as hidden when visualizing the network
  hiddenIcon: "⇒"
  # The "icon" used to mark a Stargate as not hidden when visualizing the network
  notHiddenIcon: "⇄"
  # The "icon" used to mark a Stargate as always open when visualizing the network
  alwaysOpenIcon: "⬛"
  # The "icon" used to mark a Stargate as not always open when visualizing the network
  notAlwaysOpenIcon: "⬜"
  # The "icon" used to mark a Stargate as random open when visualizing the network
  randomIcon: "↯"
  # The "icon" used to mark a Stargate as not random open when visualizing the network
  notRandomIcon: "↠"
  # The "icon" used for a right arrow. Used to display a Stargate's destination during visualization
  arrowRightIcon: "->"
  # The "icon" used to replace any spaces in Stargate or network names
  spaceReplacementIcon: "⚊"
  
# |                                           [ Debug ]                                          | #
# |__     These settings are provided to help developers diagnose issues with this plugin.     __| #

# An internal value used by the plugin to determine how old your config is.
# Please do not change this.
configVersion: 2