name: StargateInterfaces
version: ${project.version}
main: net.knarcraft.stargateinterfaces.StargateInterfaces
description: A UI expansion module for the Stargate Rewitten Bukkit Plugin, providing immersion exceptions (including commands and alternative (often graphical) user interfaces).
author: EpicKnarvik97, Thorinwasher
website: https://sgrewitten.org/interfaces
dependencies:
  server:
    Stargate:
      load: BEFORE
      required: true
      join-classpath: true
    StargateCustomizations:
      load: BEFORE
      required: false
      join-classpath: true
api-version: '1.20.4'