name: StargateCommand
main: net.knarcraft.stargatecommand.StargateCommand
version: 0.1.0
description: Command addon for the Stargate plugin for Bukkit
author: EpicKnarvik97
depend: [ Stargate ]
api-version: 1.18
commands:
  stargatecommand:
    aliases:
      - sgc
    description: The root command for all added commands
    usage: |
      /<command> <config/dial/visualizer/info>
      /<command> config <config option> <new value>
      /<command> dial <network name> <portal name>
      /<command> visualizer <network name>
      /<command> info
permissions:
  stargate.command.config:
    description: Allows the use of /sgc config
    default: false
  stargate.command.dial:
    description: Allows the use of /sgc dial
    default: op
  stargate.command.visualizer:
    description: Allows the use of /sgc visualizer
    default: op
  stargate.command.info:
    description: Allows the use of /sgc info
    default: op