name: StargateCommand
main: net.knarcraft.stargatecommand.StargateCommand
version: 0.1.0
description: Command addon for the Stargate plugin for Bukkit
author: EpicKnarvik97
depend: [ Stargate ]
api-version: 1.18
commands:
  stargatecommand:
    aliases:
      - sgc
    description: The root command for all added commands
    usage: |
      /<command> <config/?>
      /<command> config <config option> <new value>
permissions:
  stargate.command.config:
    description: Allow the user of /sgc config
    default: false